baseURL = "https://ralphsn.github.io/official-hugo/"
languageCode = "zh-TW"
title = "遊戲夢想實踐者"

[params]
logo = "assets/images/logo-thin.png"

[menu]
  [[menu.main]]
    name = "關於我們"
    url = "#about"
    weight = 1
  [[menu.main]]
    name = "服務項目"
    url = "#service"
    weight = 2
  [[menu.main]]
    name = "作品資訊"
    url = "#works"
    weight = 3
  [[menu.main]]
    name = "聯絡我們"
    url = "#footer"
    weight = 4

[taxonomies]


